In [1]:
import pandas as pd

In [2]:
train_file, val_file, test_file = 'turing_AA_train.csv', 'turing_AA_validate.csv', 'turing_AA_test.csv'
train, val, test = pd.read_csv(train_file), pd.read_csv(val_file), pd.read_csv(test_file)

In [3]:
train['train'] = 1
test['train'] = 0

In [8]:
train

,Unnamed: 0,Generation,label,From,train,author,content,content_tfidf,avg_len,len_text,...,f_e_3,f_e_4,f_e_5,f_e_6,f_e_7,f_e_8,f_e_9,f_e_10,f_e_11,richness
0,0,' of paying more than ps1bn in fines to insure...,gpt2_pytorch,7,1,gpt2_pytorch,' of paying more than ps1bn in fines to insure...,' pay ps1bn fine insur accus fraud.in statemen...,6.360215,1368.0,...,0.0,0.013158,0.009503,0.0,0.003655,0.000000,0.000000,0.000000,0.00000,1.0
1,1,'dead sea shrinking by 1 meter every year the ...,gpt2_small,8,1,gpt2_small,'dead sea shrinking by 1 meter every year the ...,'dead sea shrink 1 meter everi year indian exp...,5.701657,1212.0,...,0.0,0.018977,0.009076,0.0,0.004125,0.000000,0.000000,0.000000,0.00000,1.0
2,2,a blow to the head makes an instant hero in in...,fair_wmt19,2,1,fair_wmt19,a blow to the head makes an instant hero in in...,"blow head make instant hero india head , natio...",5.918552,1528.0,...,0.0,0.011780,0.018979,0.0,0.003272,0.000000,0.000000,0.000000,0.00000,1.0
3,3,"' ethereum release was released on april 18th,...",gpt2_pytorch,7,1,gpt2_pytorch,"' ethereum release was released on april 18th,...","' ethereum releas wa releas april 18th , 2014....",5.396825,402.0,...,0.0,0.017413,0.054726,0.0,0.004975,0.000000,0.000000,0.000000,0.00000,1.0
4,4,government sets up co-ordination panel to spee...,fair_wmt19,2,1,fair_wmt19,government sets up co-ordination panel to spee...,govern set co-ordin panel speed coal project -...,5.948113,1472.0,...,0.0,0.012228,0.010870,0.0,0.002717,0.000000,0.000679,0.000679,0.00000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112199,112199,'reliance fixed horizon fund ix xvi - ivd non-...,grover_large,12,1,grover_large,'reliance fixed horizon fund ix xvi - ivd non-...,'relianc fix horizon fund ix xvi - ivd non-cou...,5.615385,85.0,...,0.0,0.000000,0.000000,0.0,0.023529,0.000000,0.000000,0.000000,0.00000,1.0
112200,112200,'spring pheasant count in north dakota provide...,xlnet_base,18,1,xlnet_base,'spring pheasant count in north dakota provide...,'spring pheasant count north dakota provid opt...,5.350000,126.0,...,0.0,0.000000,0.000000,0.0,0.015873,0.000000,0.000000,0.000000,0.00000,1.0
112201,112201,'the city's civil rights division has agreed t...,gpt2_pytorch,7,1,gpt2_pytorch,'the city's civil rights division has agreed t...,'the citi 's civil right divis ha agre pay man...,5.875676,1271.0,...,0.0,0.016522,0.013375,0.0,0.007081,0.000000,0.000787,0.000787,0.00236,1.0
112202,112202,'hsbc banker arrested at jfk airport for money...,gpt2_large,5,1,gpt2_large,'hsbc banker arrested at jfk airport for money...,'hsbc banker arrest jfk airport money launder ...,5.370370,687.0,...,0.0,0.013100,0.007278,0.0,0.010189,0.001456,0.000000,0.000000,0.00000,1.0
112203,112203,birla sun life pure value direct fund-growth e...,gpt2_large,5,1,gpt2_large,birla sun life pure value direct fund-growth e...,birla sun life pure valu direct fund-growth eq...,6.629630,411.0,...,0.0,0.026764,0.000000,0.0,0.009732,0.000000,0.000000,0.000000,0.00000,1.0

In [4]:
train['train'] , test['train']

(0         1
 1         1
 2         1
 3         1
 4         1
          ..
 112199    1
 112200    1
 112201    1
 112202    1
 112203    1
 Name: train, Length: 112204, dtype: int64,
 0        0
 1        0
 2        0
 3        0
 4        0
         ..
 37352    0
 37353    0
 37354    0
 37355    0
 37356    0
 Name: train, Length: 37357, dtype: int64)

In [9]:
df = pd.concat([train, test], ignore_index=True)

In [10]:
df.to_csv('turing_AA_train_test.csv', sep=',')

In [11]:
pd.read_csv('turing_AA_train_test.csv')

,Unnamed: 0,Unnamed: 0.1,Generation,label,From,train,author,content,content_tfidf,avg_len,...,f_e_3,f_e_4,f_e_5,f_e_6,f_e_7,f_e_8,f_e_9,f_e_10,f_e_11,richness
0,0,0,' of paying more than ps1bn in fines to insure...,gpt2_pytorch,7,1,gpt2_pytorch,' of paying more than ps1bn in fines to insure...,' pay ps1bn fine insur accus fraud.in statemen...,6.360215,...,0.000000,0.013158,0.009503,0.000000,0.003655,0.000000,0.000000,0.000000,0.0,1.0
1,1,1,'dead sea shrinking by 1 meter every year the ...,gpt2_small,8,1,gpt2_small,'dead sea shrinking by 1 meter every year the ...,'dead sea shrink 1 meter everi year indian exp...,5.701657,...,0.000000,0.018977,0.009076,0.000000,0.004125,0.000000,0.000000,0.000000,0.0,1.0
2,2,2,a blow to the head makes an instant hero in in...,fair_wmt19,2,1,fair_wmt19,a blow to the head makes an instant hero in in...,"blow head make instant hero india head , natio...",5.918552,...,0.000000,0.011780,0.018979,0.000000,0.003272,0.000000,0.000000,0.000000,0.0,1.0
3,3,3,"' ethereum release was released on april 18th,...",gpt2_pytorch,7,1,gpt2_pytorch,"' ethereum release was released on april 18th,...","' ethereum releas wa releas april 18th , 2014....",5.396825,...,0.000000,0.017413,0.054726,0.000000,0.004975,0.000000,0.000000,0.000000,0.0,1.0
4,4,4,government sets up co-ordination panel to spee...,fair_wmt19,2,1,fair_wmt19,government sets up co-ordination panel to spee...,govern set co-ordin panel speed coal project -...,5.948113,...,0.000000,0.012228,0.010870,0.000000,0.002717,0.000000,0.000679,0.000679,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149556,149556,37352,new surveillance technology allows cops to tap...,fair_wmt19,2,0,fair_wmt19,new surveillance technology allows cops to tap...,new surveil technolog allow cop tap ani secur ...,6.335000,...,0.000000,0.006139,0.017735,0.000000,0.002046,0.000000,0.000000,0.000000,0.0,1.0
149557,149557,37353,' s fda accepts glenmark's nda for pain killer...,transfo_xl,16,0,transfo_xl,' s fda accepts glenmark's nda for pain killer...,' fda accept glenmark 's nda pain killer drug ...,5.920904,...,0.000000,0.008987,0.007353,0.000000,0.004085,0.000000,0.000817,0.000817,0.0,1.0
149558,149558,37354,fbi director james comey meets with senate int...,xlnet_large,19,0,xlnet_large,fbi director james comey meets with senate int...,fbi director jame comey meet senat intellig co...,6.282051,...,0.000000,0.000352,0.000704,0.000352,0.000352,0.000000,0.000000,0.000000,0.0,1.0
149559,149559,37355,'7-eleven arremete contra un propietario que s...,transfo_xl,16,0,transfo_xl,'7-eleven arremete contra un propietario que s...,' 7-eleven arremet contra un propietario que s...,5.228395,...,0.000000,0.006944,0.003968,0.000992,0.005952,0.000992,0.000992,0.000992,0.0,1.0
149560,149560,37356,"'narendra modi needs a bit of shivraj singh,ra...",xlnet_large,19,0,xlnet_large,"'narendra modi needs a bit of shivraj singh,ra...","'narendra modi need bit shivraj singh , raman ...",5.583120,...,0.000389,0.000777,0.000389,0.000389,0.001943,0.000389,0.000389,0.000389,0.0,1.0